# Site settings
title: Nathan Tatum
description: 'i dig data and the outdoors'
url: 'http://nathantatum.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Nathan Tatum'
  # email: nathan@nathantatum.com
  twitter_username: nathantatum
  facebook_username: nathantatum
  github_username:  nathantatum
  linkedin_username:  nathantatum

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
